import{i as u,S as f}from"./assets/vendor-7b6bee67.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const p="https://pixabay.com/api/",d="42556407-9285cdd9fd7b0b350af3a40b2",c=document.querySelector(".loader");function g(o){const e=new URLSearchParams({key:d,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return c.style.display="block",fetch(`${p}?${e}`).then(t=>{if(!t.ok)throw new Error("Network response was not OK!");return t.json()}).then(t=>(c.style.display="none",t.hits.length===0&&(u.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),console.error("error")),t)).catch(t=>console.error("Error fetching data:",t))}function h(o){return o.hits.map(e=>`<div class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="gallery-image-info">
          <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
          <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
          <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
          <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
      </div>
  </div>`).join("")}const y=new f(".gallery-link",{captionsData:"alt",captionDelay:250}),i=document.querySelector("#searchForm"),l=document.querySelector(".gallery");let m="";i.addEventListener("submit",b);function b(o){o.preventDefault(),l.innerHTML="",m=i.elements.searchQuery.value.trim(),g(m).then(e=>{const t=h(e);l.insertAdjacentHTML("beforeend",t),y.refresh()}).catch(e=>console.error("Error fetching data:",e)).finally(()=>{i.elements.searchQuery.value=""})}
//# sourceMappingURL=commonHelpers.js.map
